### ISSUE TITLE
编译后乱码

### ISSUE THREAD

**Issue by gcxtx01** [Yong-An-Dang/nuclei-plus#1]
![image](https://user-images.githubusercontent.com/82226301/192746941-5efc7430-29ac-44f9-b367-21c1cd8eb1de.png)

**Comment by G3G4X5X6** [comment]
看看IDE的编码？或者指定编码启动？
```bash
 -Dfile.encoding=UTF-8

````

**Comment by G3G4X5X6** [comment]
###  解决办法：
-  -Dfile.encoding=GBK
- -Dfile.encoding=GB2312
- -Dfile.encoding=GB18030 
- -Dfile.encoding=UTF-8

可以多尝试几个，应该总有一个编码可行
