### ISSUE TITLE
Win 中文显示异常

### ISSUE THREAD

**Issue by yz1639** [Yong-An-Dang/nuclei-plus#18]
java 版本：11.0.2
<hr>
win  版本：11

![image](https://github.com/Yong-An-Dang/nuclei-plus/assets/44149984/420119e0-75e5-4b89-bd15-cdf63af81ee6)

<hr>
异常界面截图：

![image](https://github.com/Yong-An-Dang/nuclei-plus/assets/44149984/8a051c0e-8cba-43c9-8650-586e432b36d0)

项目配置输入中文后保存，再次打开编辑也是乱码：

![image](https://github.com/Yong-An-Dang/nuclei-plus/assets/44149984/fd59933d-4e25-4dd6-bdca-25b2d8a7ad6f)

**Comment by G3G4X5X6** [comment]
已修复，稍后发布修复版本

**Comment by G3G4X5X6** [comment]
已发布修复版本
