### ISSUE TITLE
【Think & TODO】

### ISSUE THREAD

**Issue by G3G4X5X6** [Yong-An-Dang/nuclei-plus#19]
__大家有什么想法和期待实现的功能，欢迎到这里提出和讨论 👉 https://github.com/Yong-An-Dang/nuclei-plus/discussions/20__
<hr>

Everyone is welcome to put forward your ideas, problems encountered and features you are looking forward to!

__不要在这里提BUG，我有时候会漏掉的。__

**Comment by qwerkilo** [comment]
712报错，换回7.0没问题
`C:\Users\qwerkilo\Downloads>java -jar nuclei-7.1.2.jar
SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#noProviders for further details.`

**Comment by G3G4X5X6** [comment]
> 712报错，换回7.0没问题 `C:\Users\qwerkilo\Downloads>java -jar nuclei-7.1.2.jar SLF4J: No SLF4J providers were found. SLF4J: Defaulting to no-operation (NOP) logger implementation SLF4J: See http://www.slf4j.org/codes.html#noProviders for further details.`

![image](https://github.com/Yong-An-Dang/nuclei-plus/assets/87740076/77934dfe-219f-4005-840b-92549566fcc4)
这个提示不影响正常启动的呀

**Comment by G3G4X5X6** [comment]
> 712报错，换回7.0没问题 `C:\Users\qwerkilo\Downloads>java -jar nuclei-7.1.2.jar SLF4J: No SLF4J providers were found. SLF4J: Defaulting to no-operation (NOP) logger implementation SLF4J: See http://www.slf4j.org/codes.html#noProviders for further details.`

更新了，重新下载试试

**Comment by ChendCharlie** [comment]
环境mac java11 右键配置无反应
![1702885911868](https://github.com/Yong-An-Dang/nuclei-plus/assets/109772602/e1e4a1da-376b-45b9-bbb5-fff0722ed2ec)

**Comment by G3G4X5X6** [comment]
> 环境mac java11 右键配置无反应 ![1702885911868](https://private-user-images.githubusercontent.com/109772602/291187279-e1e4a1da-376b-45b9-bbb5-fff0722ed2ec.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI4OTYyNDQsIm5iZiI6MTcwMjg5NTk0NCwicGF0aCI6Ii8xMDk3NzI2MDIvMjkxMTg3Mjc5LWUxZTRhMWRhLTM3NmItNDViOS1iYmI1LWZmZjA3MjJlZDJlYy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxOFQxMDM5MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZjFkM2NhYzhlY2Y1NWNhYTc0ZmQ1NjViZmZjMDRjNTNkZGUyYWQ0ODgzNDY0NjJjNWQ0ZjdmNGExYWI3ZTVkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ZV-K4h7u9g3OLxzGdB6N9pmcOFYw95ryMXG1mB12YPc)

Mac系统得等我什么时候整个虚拟机才能看看了 😢

**Comment by G3G4X5X6** [comment]
这里是个引导Issue哈，不要在这个issue提bug，可能会看不到。


大家有什么想法和期待实现的功能，欢迎到这里提出和讨论 👉 #20
