### ISSUE TITLE
setting->template处添加常用标签分组

### ISSUE THREAD

**Issue by gcxtx01** [Yong-An-Dang/nuclei-plus#2]
这块再加个列表的功能，我把常用的template 添加到分组里，用的时候方便选择，比如把致远oa和泛微oa的标签都放到一起，我用的时候直接选择相应的分组列表就行了。
![06ce2f12a42de9f4fea2a6cc078c780](https://user-images.githubusercontent.com/82226301/192749240-5654da75-bca6-4612-b5b4-b1a6fdcb9027.jpg)

**Comment by G3G4X5X6** [comment]
### 已实现
![image](https://user-images.githubusercontent.com/87740076/216819647-13f7a20c-7626-4892-b96b-ffc9ee869f93.png)

![image](https://user-images.githubusercontent.com/87740076/216819635-6f325139-5d83-4549-877c-df317a5ea3cd.png)
