### ISSUE TITLE
mac把nucei放在bin目录下，提示bash: nuclei: command not found

### ISSUE THREAD

**Issue by wlaq-su** [Yong-An-Dang/nuclei-plus#22]
![image](https://github.com/Yong-An-Dang/nuclei-plus/assets/65948791/d0e59563-ae12-4552-987f-bc6c42eabaeb)

**Comment by G3G4X5X6** [comment]
把nucei放在bin目录下，要重启软件生效哦

**Comment by G3G4X5X6** [comment]
还有问题麻烦贴上日志哈

**Comment by wlaq-su** [comment]
2023/12/19 17:08:59,706 DEBUG [SwingWorker-pool-1-thread-1] (ExtractedNative.java:124:doInit) - Copied [resources/com/pty4j/native/darwin/libpty.dylib] in 18 ms
2023/12/19 17:08:59,706 INFO [SwingWorker-pool-1-thread-1] (ExtractedNative.java:128:doInit) - Extracted pty4j native in 18 ms
2023/12/19 17:08:59,831 DEBUG [TerminalEmulator-Nuclei-Console] (JediEmulator.java:109:processEscapeSequence) - Control Sequence (parsed: ESC[?1034h, raw: ESC[?1034h)
2023/12/19 17:08:59,835 INFO [TerminalEmulator-Nuclei-Console] (JediEmulator.java:1082:setModeEnabled) - Setting mode EightBitInput enabled = true
2023/12/19 17:08:59,835 WARN [TerminalEmulator-Nuclei-Console] (TerminalMode.java:110:setEnabled) - Mode EightBitInput is not implemented, setting to true
2023/12/19 17:09:00,351 DEBUG [TerminalEmulator-Nuclei-Console] (JediEmulator.java:109:processEscapeSequence) - Control Sequence (parsed: ESC[K, raw: ESC[K)
2023-12-19 17:09:04.123 java[17889:508497] TSM AdjustCapsLockLEDForKeyTransitionHandling - _ISSetPhysicalKeyboardCapsLockLED Inhibit
2023/12/19 17:09:09,767 DEBUG [AWT-EventQueue-0] (TerminalPanel.java:711:establishFontMetrics) - charHeight=23->21, descent=5->4
2023/12/19 17:09:09,767 DEBUG [AWT-EventQueue-0] (ConsolePanel.java:56:createTtyConnector) - {PATH=/bin/zsh:/Library/Java/JavaVirtualMachines/jdk-1.8.jdk/Contents/Home/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/Library/Frameworks/Python.framework/Versions/3.12/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin, MANPATH=/opt/homebrew/share/man::, JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk-1.8.jdk/Contents/Home, TERM=xterm-256color, LANG=zh_CN.UTF-8, HOMEBREW_PREFIX=/opt/homebrew, LOGNAME=alensu, HOMEBREW_REPOSITORY=/opt/homebrew, XPC_SERVICE_NAME=0, PWD=/Users/alensu/Desktop/渗透测试/GUI_Tools/Java_path/Java_19/bin, TERM_PROGRAM_VERSION=452, INFOPATH=/opt/homebrew/share/info:, _=/Users/alensu/Desktop/渃�逃�浃�诃�/GUI_Tools/Java_path/Java_19/bin/./java, __CFBundleIdentifier=com.apple.Terminal, SHELL=/bin/zsh, TERM_PROGRAM=Apple_Terminal, HOMEBREW_CELLAR=/opt/homebrew/Cellar, OLDPWD=/Users/alensu/Desktop/渗透测试/GUI_Tools/Java_path/Java_19/bin, SECURITYSESSIONID=186a3, USER=alensu, LaunchInstanceID=707195D8-38C9-4C83-AF2D-212B9A80B0B7, TMPDIR=/var/folders/sj/kl4ft4256n3_8fk_06rnp0x40000gn/T/, SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.cajLLvGmG9/Listeners, XPC_FLAGS=0x0, TERM_SESSION_ID=52BC794F-94A3-458A-8777-50C913BE6BAB, __CF_USER_TEXT_ENCODING=0x1F5:0x19:0x34, HOME=/Users/alensu, SHLVL=1}
2023/12/19 17:09:09,861 DEBUG [TerminalEmulator-Nuclei-Console] (JediEmulator.java:109:processEscapeSequence) - Control Sequence (parsed: ESC[?1034h, raw: ESC[?1034h)
2023/12/19 17:09:09,861 INFO [TerminalEmulator-Nuclei-Console] (JediEmulator.java:1082:setModeEnabled) - Setting mode EightBitInput enabled = true
2023/12/19 17:09:09,861 WARN [TerminalEmulator-Nuclei-Console] (TerminalMode.java:110:setEnabled) - Mode EightBitInput is not implemented, setting to true
2023/12/19 17:09:09,972 DEBUG [TerminalEmulator-Nuclei-Console] (JediEmulator.java:109:processEscapeSequence) - Control Sequence (parsed: ESC[K, raw: ESC[K)
2023/12/19 17:09:16,708 DEBUG [AWT-EventQueue-0] (NucleiYamlCompletionProvider.java:15:<init>) - Load BashCompletionProvider
2023/12/19 17:09:16,713 DEBUG [AWT-EventQueue-0] (EditorPanel.java:254:initSearchDialogs) - initSearchDialogs

**Comment by wlaq-su** [comment]
> 还有问题麻烦贴上日志哈

报错日志回复你了 ，我是用在java19的目录下执行的jar包，默认java8

**Comment by wlaq-su** [comment]
> 把nucei放在bin目录下，要重启软件生效哦

重启了 也不行

**Comment by G3G4X5X6** [comment]
> 默认java8

不支持jdk8， JDK11+

**Comment by G3G4X5X6** [comment]
感谢反馈问题，谢谢！@wlaq-su

问题已在 [nuclei-plus_v7.1.3](https://github.com/Yong-An-Dang/nuclei-plus/releases/tag/v7.1.3) 版本中修复， 可下载最新发布包试试。

**Comment by wlaq-su** [comment]
> > 默认java8
> 
> 不支持jdk8，JDK11+

我在jdk19的目录下运行的哥

**Comment by G3G4X5X6** [comment]
> > > 默认java8
> > 
> > 不支持jdk8，JDK11+
> 
> 我在jdk19的目录下运行的哥

嗯嗯，试试最新版本
