### ISSUE TITLE
环境win11 java11 打开jar包一直在正在加载中

### ISSUE THREAD

**Issue by ewfubwefwe** [Yong-An-Dang/nuclei-plus#23]
![image](https://github.com/Yong-An-Dang/nuclei-plus/assets/91933542/1004183e-50d4-47f0-8a3b-33da481ebdaf)

**Comment by G3G4X5X6** [comment]
贴上日志看看，谢谢

**Comment by ewfubwefwe** [comment]
[nuclei-plus.log](https://github.com/Yong-An-Dang/nuclei-plus/files/13716484/nuclei-plus.log)
日志文件

**Comment by G3G4X5X6** [comment]
是不是最新版的

**Comment by ewfubwefwe** [comment]
是最新版

**Comment by G3G4X5X6** [comment]
> 是最新版

尬住，又没有报错

**Comment by G3G4X5X6** [comment]
使用最新版试试
