### ISSUE TITLE
编译后乱码

### ISSUE THREAD

**Issue by kN6jq** [Yong-An-Dang/nuclei-plus#24]
![image](https://github.com/Yong-An-Dang/nuclei-plus/assets/27048404/8710a36f-c66c-4d67-b590-7ac9860d707f)

尝试过 https://github.com/Yong-An-Dang/nuclei-plus/issues/1

**Comment by G3G4X5X6** [comment]
奇怪，好像是代码里面的字符串变量在你的系统上乱码了

**Comment by G3G4X5X6** [comment]
这个没法复现，看看有没有路过的大佬指点下了

**Comment by G3G4X5X6** [comment]
国际化：bar.tool.motto

尝试修复乱码的问题 #24

**Comment by G3G4X5X6** [comment]
下一个版本

**Comment by G3G4X5X6** [comment]
@kN6jq @gcxtx01 终于知道为啥乱码了，解决方法：
`mvn clean package -DskipTests -Dproject.build.sourceEncoding=UTF-8`
