### ISSUE TITLE
mac运行任务report报告也没有生成

### ISSUE THREAD

**Issue by wlaq-su** [Yong-An-Dang/nuclei-plus#26]

**Comment by G3G4X5X6** [comment]
贴上运行情况，Running面板的输出

**Comment by wlaq-su** [comment]
> 贴上运行情况，Running面板的输出

Exception in thread "Thread-28" org.yaml.snakeyaml.error.YAMLException: java.nio.charset.MalformedInputException: Input length = 1
	at org.yaml.snakeyaml.reader.StreamReader.update(StreamReader.java:215)
	at org.yaml.snakeyaml.reader.StreamReader.ensureEnoughData(StreamReader.java:173)
	at org.yaml.snakeyaml.reader.StreamReader.ensureEnoughData(StreamReader.java:168)
	at org.yaml.snakeyaml.reader.StreamReader.peek(StreamReader.java:123)
	at org.yaml.snakeyaml.scanner.ScannerImpl.scanToNextToken(ScannerImpl.java:1204)
	at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:320)
	at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:238)
	at org.yaml.snakeyaml.parser.ParserImpl$ParseImplicitDocumentStart.produce(ParserImpl.java:210)
	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:161)
	at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:152)
	at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:156)
	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:178)
	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:493)
	at org.yaml.snakeyaml.Yaml.loadAs(Yaml.java:486)
	at com.g3g4x5x6.nuclei.ultils.CommonUtil.getMapFromYaml(CommonUtil.java:157)
	at com.g3g4x5x6.nuclei.ultils.CommonUtil.getTemplateInfoFromPath(CommonUtil.java:199)
	at com.g3g4x5x6.nuclei.panel.tab.TemplatesPanel$12.visitFile(TemplatesPanel.java:538)
	at com.g3g4x5x6.nuclei.panel.tab.TemplatesPanel$12.visitFile(TemplatesPanel.java:533)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2725)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2797)
	at com.g3g4x5x6.nuclei.panel.tab.TemplatesPanel.walkFiles(TemplatesPanel.java:533)
	at com.g3g4x5x6.nuclei.panel.tab.TemplatesPanel.getAllTemplatesFromPath(TemplatesPanel.java:521)
	at com.g3g4x5x6.nuclei.panel.tab.TemplatesPanel.lambda$refreshDataForTable$2(TemplatesPanel.java:430)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.nio.charset.MalformedInputException: Input length = 1
	at java.base/java.nio.charset.CoderResult.throwException(CoderResult.java:274)
	at java.base/sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:339)
	at java.base/sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
	at java.base/java.io.InputStreamReader.read(InputStreamReader.java:181)
	at org.yaml.snakeyaml.reader.UnicodeReader.read(UnicodeReader.java:118)
	at org.yaml.snakeyaml.reader.StreamReader.update(StreamReader.java:180)
	... 23 more

**Comment by wlaq-su** [comment]
> 贴上运行情况，Running面板的输出

[WRN] Found 44 templates loaded with deprecated protocol syntax, update before v3 for continued support.
[WRN] Found 35 templates with syntax warning (use -validate flag for further examination)
[INF] Current nuclei version: v3.1.1 (outdated)
[INF] Current nuclei-templates version: v9.7.1 (latest)
[WRN] Scan results upload to cloud is disabled.
[INF] New templates added in latest release: 0
[INF] Templates loaded for current scan: 7486
[INF] Executing 7341 signed templates from projectdiscovery/nuclei-templates
[WRN] Executing 163 unsigned templates. Use with caution.
[INF] Targets loaded for current scan: 9
[INF] Templates clustered: 1254 (Reduced 10998 Requests)
[ptr-fingerprint] [dns] [info] 41.214.154.27.in-addr.arpa [41.214.154.27.broad.xm.fj.dynamic.163data.com.cn.]
[INF] Skipped 114.55.33.148:80 from target list as found unresponsive 30 times
[INF] Skipped 47.104.243.88:80 from target list as found unresponsive 32 times
[INF] Skipped 121.40.84.21:80 from target list as found unresponsive 32 times
[INF] Using Interactsh Server: oast.fun
[INF] Skipped 119.45.159.83:80 from target list as found unresponsive 30 times
[INF] Skipped 119.45.166.54:80 from target list as found unresponsive 30 times
[INF] Skipped 27.154.214.41:6060 from target list as found unresponsive 30 times
[INF] Skipped 60.182.130.77:81 from target list as found unresponsive 30 times
[INF] Skipped 118.31.3.181:80 from target list as found unresponsive 31 times
[INF] Skipped 120.79.190.75:81 from target list as found unresponsive 31 times
bash-3.2$ 
e before v3 for continued support. loaded with deprecated protocol syntax, updat 
bash: [WRN]: command not found
urther examination)nd 35 templates with syntax warning (use -validate flag for f 
bash: syntax error near unexpected token `('
bash-3.2$ [INF] Current nuclei version: v3.1.1 (outdated)
bash: syntax error near unexpected token `('
bash-3.2$ [INF] Current nuclei-templates version: v9.7.1 (latest)
[WRN] Scan results upload to cloud is disabled.
[INF] New templates added in latest release: 0
[INF] Templates loaded for current scan: 7486
[INF] Executing 7341 signed templates from projectdiscovery/nuclei-templates
[WRN] Executing 163 unsigned templates. Use with caution.
[INF] Targets loaded for current scan: 9
[INF] Templates clustered: 1254 (Reduced 10998 Requests)
[ptr-fingerprint] [dns] [info] 41.214.154.27.in-addr.arpa [41.214.154.27.broad.xm.fj.dynamic.163data.com.cn.]
[INF] Skipped 114.55.33.148:80 from target list as found unresponsive 30 times
[INF] Skipped 47.104.243.88:80 from target list as found unresponsive 32 times
[INF] Skipped 121.40.84.21:80 from target list as found unresponsive 32 times
[INF] Using Interactsh Server: oast.fun
[INF] Skipped bash: syntax error near unexpected token `('
bash-3.2$ [WRN] Scan results upload to cloud is disabled.
bash: [WRN]: command not found
bash-3.2$ [INF] New templates added in latest release: 0
bash: [INF]: command not found
bash-3.2$ [INF] Templates loaded for current scan: 7486
bash: [INF]: command not found
plates.2$ [INF] Executing 7341 signed templates from projectdiscovery/nuclei-tem 
bash: [INF]: command not found
bash-3.2$ [WRN] Executing 163 unsigned templates. Use with caution.
bash: [WRN]: command not found
bash-3.2$ [INF] Targets loaded for current scan: 9
bash: [INF]: command not found
bash-3.2$ [INF] Templates clustered: 1254 (Reduced 10998 Requests)
bash: syntax error near unexpected token `('
27.broad.xm.fj.dynamic.163data.com.cn.]] 41.214.154.27.in-addr.arpa [41.214.154. 
bash: [ptr-fingerprint]: command not found
30 times$ [INF] Skipped 114.55.33.148:80 from target list as found unresponsive  
bash: [INF]: command not found
32 times$ [INF] Skipped 47.104.243.88:80 from target list as found unresponsive  
bash: [INF]: command not found
2 times2$ [INF] Skipped 121.40.84.21:80 from target list as found unresponsive 3 
bash: [INF]: command not found
bash-3.2$ [INF] Using Interactsh Server: oast.fun
bash: [INF]: command not found
30 times$ [INF] Skipped 119.45.159.83:80 from target list as found unresponsive  
bash: [INF]: command not found
30 times$ [INF] Skipped 119.45.166.54:80 from target list as found unresponsive  
bash: [INF]: command not found
 30 times060 from target list [IN30.77:81 from target list as found unresponsive 
bash: [INF]: command not found
1 times2$ [INF] Skipped 118.31.3.181:80 from target list as found unresponsive 3 
bash: [INF]: command not found
31 times$ [INF] Skipped 120.79.190.75:81 from target list as found unresponsive

**Comment by G3G4X5X6** [comment]
![image](https://github.com/Yong-An-Dang/nuclei-plus/assets/87740076/c3d75c29-c609-48b8-944d-72db79ff94f8)

能不能像这样子测试下几个简单info模板，截图我看看

**Comment by wlaq-su** [comment]
> ![image](https://private-user-images.githubusercontent.com/87740076/291864142-c3d75c29-c609-48b8-944d-72db79ff94f8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxMTkxODUsIm5iZiI6MTcwMzExODg4NSwicGF0aCI6Ii84Nzc0MDA3Ni8yOTE4NjQxNDItYzNkNzVjMjktYzYwOS00OGI4LTk0NGQtNzJkYjc5ZmY5NGY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIxVDAwMzQ0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk3N2NlOTlkMGVmOTM3NWRkNjhhYTVkYzM3MmY4MTMxZWQ3ZTc5YzhmYTk0OGU3ZDdhZGQ1ZjdmNDVjZTUxZWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jJ8nikJ__ufTHugIoTPhYZT_wIdTRNgBbNubqfjpstE)
> 
> 能不能像这样子测试下几个简单info模板，截图我看看

**Comment by wlaq-su** [comment]
![image](https://github.com/Yong-An-Dang/nuclei-plus/assets/65948791/50caea13-3c79-4dfb-9770-4edf85ab8ba5)

**Comment by G3G4X5X6** [comment]
![image](https://github.com/Yong-An-Dang/nuclei-plus/assets/87740076/0c1ebbcf-6405-4775-958b-83d8c01dab04)


不应该呀，命令都执行成功了，你看看执行的命令行的参数指定的报告目录对不对

**Comment by wlaq-su** [comment]
> ![image](https://private-user-images.githubusercontent.com/87740076/292065116-0c1ebbcf-6405-4775-958b-83d8c01dab04.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxMjQ1MDEsIm5iZiI6MTcwMzEyNDIwMSwicGF0aCI6Ii84Nzc0MDA3Ni8yOTIwNjUxMTYtMGMxZWJiY2YtNjQwNS00Nzc1LTk1OGItODNkOGMwMWRhYjA0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIxVDAyMDMyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI2OGQ0MDcwNzMwMTc3NWRmNTZkZjNkOTUwODA3NDRhMDAwMjI2MTUzZTg0NTNjMWVkYTc1M2VlZGNmYzYwYTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Rpatycp1v3strHEhqdOmfaiFJyO361lq4uaYQQLL4Y8)
> 
> 不应该呀，命令都执行成功了，你看看执行的命令行的参数指定的报告目录对不对

我的mac好像都没有执行生产报告的命令

**Comment by wlaq-su** [comment]
> ![image](https://private-user-images.githubusercontent.com/87740076/292065116-0c1ebbcf-6405-4775-958b-83d8c01dab04.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxMjQ1MDEsIm5iZiI6MTcwMzEyNDIwMSwicGF0aCI6Ii84Nzc0MDA3Ni8yOTIwNjUxMTYtMGMxZWJiY2YtNjQwNS00Nzc1LTk1OGItODNkOGMwMWRhYjA0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIxVDAyMDMyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI2OGQ0MDcwNzMwMTc3NWRmNTZkZjNkOTUwODA3NDRhMDAwMjI2MTUzZTg0NTNjMWVkYTc1M2VlZGNmYzYwYTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Rpatycp1v3strHEhqdOmfaiFJyO361lq4uaYQQLL4Y8)
> 
> 不应该呀，命令都执行成功了，你看看执行的命令行的参数指定的报告目录对不对

我执行命令他不会自动生成报告吗

**Comment by wlaq-su** [comment]
> ![image](https://private-user-images.githubusercontent.com/87740076/292065116-0c1ebbcf-6405-4775-958b-83d8c01dab04.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxMjQ1MDEsIm5iZiI6MTcwMzEyNDIwMSwicGF0aCI6Ii84Nzc0MDA3Ni8yOTIwNjUxMTYtMGMxZWJiY2YtNjQwNS00Nzc1LTk1OGItODNkOGMwMWRhYjA0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIxVDAyMDMyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI2OGQ0MDcwNzMwMTc3NWRmNTZkZjNkOTUwODA3NDRhMDAwMjI2MTUzZTg0NTNjMWVkYTc1M2VlZGNmYzYwYTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Rpatycp1v3strHEhqdOmfaiFJyO361lq4uaYQQLL4Y8)
> 
> 不应该呀，命令都执行成功了，你看看执行的命令行的参数指定的报告目录对不对

需要手动加上执行生成报告的命令吗

**Comment by wlaq-su** [comment]
> ![image](https://private-user-images.githubusercontent.com/87740076/292065116-0c1ebbcf-6405-4775-958b-83d8c01dab04.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxMjQ1MDEsIm5iZiI6MTcwMzEyNDIwMSwicGF0aCI6Ii84Nzc0MDA3Ni8yOTIwNjUxMTYtMGMxZWJiY2YtNjQwNS00Nzc1LTk1OGItODNkOGMwMWRhYjA0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIxVDAyMDMyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI2OGQ0MDcwNzMwMTc3NWRmNTZkZjNkOTUwODA3NDRhMDAwMjI2MTUzZTg0NTNjMWVkYTc1M2VlZGNmYzYwYTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Rpatycp1v3strHEhqdOmfaiFJyO361lq4uaYQQLL4Y8)
> 
> 不应该呀，命令都执行成功了，你看看执行的命令行的参数指定的报告目录对不对

![image](https://github.com/Yong-An-Dang/nuclei-plus/assets/65948791/db631c43-64b8-427e-b478-904d3847afc1)
我的报告位置没改过

**Comment by G3G4X5X6** [comment]
你就把Running面板当普通cmd执行nuclei扫描试试，就是自己填充下参数，看看能不能扫完正常出报告。（这个程序也只是把nuclei的命令行参数拼接下执行的，没什么特别的呀，不知道为什么不生成报告，估计得等我弄个mac虚拟机复现下才行了）

**Comment by G3G4X5X6** [comment]
无法复现，暂时关闭
