### ISSUE TITLE
运行模板后自动给url后门加斜杠

### ISSUE THREAD

**Issue by kN6jq** [Yong-An-Dang/nuclei-plus#27]
[INF] Nuclei Engine Version: v3.1.2

![image](https://github.com/Yong-An-Dang/nuclei-plus/assets/27048404/baf3af92-70e9-48ae-a558-762309c62f2b)

nuclei -config C:\Users\hello\.nuclei-plus\projects\default\temp\config_2023-12-20_09-31-35.yaml -markdown-export C:\U
sers\hello\.nuclei-plus\projects\default\report --debug-req

![image](https://github.com/Yong-An-Dang/nuclei-plus/assets/27048404/7147af56-b6cf-4c88-9f66-b3072bbc47ed)

**Comment by G3G4X5X6** [comment]
> [INF] Nuclei Engine Version: v3.1.2
> 
> ![image](https://private-user-images.githubusercontent.com/27048404/291756826-baf3af92-70e9-48ae-a558-762309c62f2b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwNTQ4ODEsIm5iZiI6MTcwMzA1NDU4MSwicGF0aCI6Ii8yNzA0ODQwNC8yOTE3NTY4MjYtYmFmM2FmOTItNzBlOS00OGFlLWE1NTgtNzYyMzA5YzYyZjJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIwVDA2NDMwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYzN2QzMmE5YWZmNDUwNmMwOTcxZTk1MTc0ZWViYWE0ZDk0Y2Q5YzkyNTEwMTU4NzA3Mjk2YmRmNjk3YjcxOGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Mw5836aJ1dAG2cnJeKN1i11eEGCQ2sbDMlSrRCPTiNg)
> 
> nuclei -config C:\Users\hello.nuclei-plus\projects\default\temp\config_2023-12-20_09-31-35.yaml -markdown-export C:\U sers\hello.nuclei-plus\projects\default\report --debug-req
> 
> ![image](https://private-user-images.githubusercontent.com/27048404/291756970-7147af56-b6cf-4c88-9f66-b3072bbc47ed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwNTQ4ODEsIm5iZiI6MTcwMzA1NDU4MSwicGF0aCI6Ii8yNzA0ODQwNC8yOTE3NTY5NzAtNzE0N2FmNTYtYjZjZi00Yzg4LTlmNjYtYjMwNzJiYmM0N2VkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIwVDA2NDMwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUyNDQ2ZWRkMjAzZTZkODhjMzQ0YjhlZjUxZmUzNWQxYzBiODk0ZTg3ZGIyYTUxMGEyNmQ0OTYxNGE5ZjZmMTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NGtltJwK2XH4_JgJ8ukCH-lfuJiocrZM3byhujcLlbE)

根据yaml模板看，模板里面是没有加的，那么这个加 “/” 就是 nuclei 的行为了
