### ISSUE TITLE
BUG：NucleiConfig.java:54（version 7.5.9）

### ISSUE THREAD

**Issue by cream-sec** [Yong-An-Dang/nuclei-plus#35]
java -jar nuclei.app.jar
2024/11/13 10:37:57,769 INFO [main] (NucleiConfig.java:73:getWorkPath) - 自定义工作目录不存在，使用默认工作目录。
2024/11/13 10:37:57,771 INFO [main] (NucleiConfig.java:73:getWorkPath) - 自定义工作目录不存在，使用默认工作目录。
2024/11/13 10:37:57,773 INFO [main] (NucleiConfig.java:73:getWorkPath) - 自定义工作目录不存在，使用默认工作目录。
Exception in thread "main" java.lang.NullPointerException
	at com.g3g4x5x6.nuclei.NucleiConfig.getProperty(NucleiConfig.java:54)
	at com.g3g4x5x6.NucleiApp.main(NucleiApp.java:54)

解决方法：删除原来的.nuclei-plus目录（家目录下）

**Comment by geelph** [comment]
这个报错的原因是v7.5.9在支持国际化的时候，在nuclei.properties配置文件中添加了nuclei.locale的配置项，
使用原来的配置时，在程序初始化的时候找不到这一项就导致异常退出，因为代码中默认是从配置文件中获取语言类型，
不想删.nuclei-plus的话，在nuclei.propertis中手动加一下就行
```ini
# 国际化，指定本地语言（为空跟随系统设置）：zh_CN, en_US
nuclei.locale=zh_CN
```

**Comment by cream-sec** [comment]
谢谢师傅的回复！

**Comment by G3G4X5X6** [comment]
这才是开源的意义，大家互帮互助 👍
