### ISSUE TITLE
序号排序时顺序错乱

### ISSUE THREAD

**Issue by Klutton** [Yong-An-Dang/nuclei-plus#36]
在按照序号排序时顺序错乱，应该是因为使用字符串排序而不是数字排序导致的

![图片](https://github.com/user-attachments/assets/8b387fb6-458a-4521-86d7-7bcf5a6a7408)

**Comment by G3G4X5X6** [comment]
看截图，当前是按照严重等级排下来着，你看标题的箭头，在template_severtiy，“＃”标题那里没有排序的箭头

**Comment by geelph** [comment]
> 看截图，当前是按照严重等级排下来着，你看标题的箭头，在template_severtiy，“＃”标题那里没有排序的箭头

可能是他图没放对，直接以#进行排序，确实能复现出他文字描述的现象

**Comment by Klutton** [comment]
对不起图放错了，已经更新



> 在按照序号排序时顺序错乱，应该是因为使用字符串排序而不是数字排序导致的
> 
> ![图片](https://private-user-images.githubusercontent.com/113648660/387266784-8b387fb6-458a-4521-86d7-7bcf5a6a7408.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE5NDE1ODAsIm5iZiI6MTczMTk0MTI4MCwicGF0aCI6Ii8xMTM2NDg2NjAvMzg3MjY2Nzg0LThiMzg3ZmI2LTQ1OGEtNDUyMS04NmQ3LTdiY2Y1YTZhNzQwOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExOFQxNDQ4MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lOWY4ZTE0OGYwM2ZlOTg0ZGY5NmE0MTMxOTM3OWViNWMxZjZjZGZiNTI2MTM1YTUwMGU0ZDY3MzIyMWIxOWNhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.K_by2ycXuaHvQv47AApwquE_8-HExhtNNqfxnAfcCFw)

**Comment by G3G4X5X6** [comment]
收到，感谢反馈~ 👍

**Comment by G3G4X5X6** [comment]
已修复 #38
