### ISSUE TITLE
[FTL] Could not read config: yaml: invalid trailing UTF-8 octet

### ISSUE THREAD

**Issue by geelph** [Yong-An-Dang/nuclei-plus#37]
# 问题描述
nuclei执行扫描时出现异常退出，报错提示为：[FTL] Could not read config: yaml: invalid trailing UTF-8 octet
使用nuclie单独执行同一个模板（模板文件名称包含中文）时可以正常运行，但是执行nuclei-plus创建的config.yaml文件时也抛出同样的错误
# 问题原因
发现问题时由于文件编码格式导致的，nuclei默认以UTF-8格式读取文件，但nuclei-plus创建config.yaml文件时未指定编码方式则采用系统默认编码格式，中文系统时创建的config.yaml文件编码格式是GB2312，nuclei以utf-8方式读取时存在的中文导致乱码、抛错。
# 修复建议
在nuclei/src/main/java/com/g3g4x5x6/nuclei/ultils/CommonUtil.java中声明FileWriter对象实例时使用java.nio.charset.StandardCharsets.UTF_8指定编码格式为utf-8
类似这样处理，应该能解决：
```java
// 配置 YAML 写入器以支持 UTF-8 编码
        FileWriter writer = new FileWriter(savePath, java.nio.charset.StandardCharsets.UTF_8);
        Yaml yaml = new Yaml(new SafeConstructor(new LoaderOptions()));

        // 写入配置
        yaml.dump(config, writer);
```

**Comment by G3G4X5X6** [comment]
已修复 #38
