### ISSUE TITLE
无法下载官方模板

### ISSUE THREAD

**Issue by Objia** [Yong-An-Dang/nuclei-plus#39]
出现一个很奇怪的现象，在vmware虚拟机里面运行，不管是windows虚拟机还是linux虚拟机，程序打开后都无法正常加载官方模板，但是在宿主机（windows）运行程序却可以加载官方模板，命令行窗口也没有显示报错，指示显示加载模板的数量为0。
![无标题](https://github.com/user-attachments/assets/0dd9a6b8-8262-4b29-ac8b-9e9ef74f1c8f)

**Comment by G3G4X5X6** [comment]
有没有下载nuclei到工作目录的bin目录，同时还有刷新下载好模板先

**Comment by G3G4X5X6** [comment]
无法下载模板和这个程序无关，理论上，能正常使用nuclei，就是可以使用nuclei-plus，plus只是一个GUI封装而已

**Comment by G3G4X5X6** [comment]
先确保虚拟机中可以正常使用nuclei

**Comment by Objia** [comment]
> 无法下载模板和这个程序无关，理论上，能正常使用nuclei，就是可以使用nuclei-plus，plus只是一个GUI封装而已

感谢，解决了。之前一直以为官方模板文件是由nuclei-plus负责下载，原来官方模板是由nuclei在执行的时候下载到本地的，nuclei-plus只是读取本地保存的官方模板文件而已。之前安装了nuclei，但是并没有运行过，所以本地没有下载官方文件，导致nuclei-plus读不到。
